version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    groups:
      minor-java-dependencies:
        # group minor/patch Maven updates into one PR; do not update major versions
        # (too likely to break something)
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

      # Temporary exclusions, pending upstream fixes
      #  https://github.com/dropwizard/dropwizard/pull/11273
      - dependency-name: "ch.qos.logback:*"
        versions: [ ">=1.6.0" ]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      minor-actions-dependencies:
        # group minor/patch GHA updates into one PR; keep separate PRs for
        # major version updates so we can review them carefully
        update-types:
          - minor
          - patch
