name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version-file: .java-version
          cache: 'maven'
        env:
          # work around an issue with actions/runner setting an incorrect HOME in containers, which breaks maven caching
          # https://github.com/actions/setup-java/issues/356
          HOME: /root
      - name: Build with Maven
        run: ./mvnw -e -B verify
